apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: kargo-demo
spec:
  replicas: 4
  selector:
    matchLabels:
      app: kargo-demo
  strategy:
    blueGreen:
      activeService: kargo-demo-active
      autoPromotionEnabled: false
      previewService: kargo-demo-preview
  template:
    metadata:
      labels:
        app: kargo-demo
    spec:
      containers:
      - image: public.ecr.aws/nginx/nginx:1.27.3
        name: nginx
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: content
          readOnly: true
      volumes:
      - configMap:
          name: kargo-demo-content
        name: content
