apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: kargo-demo
spec:
  replicas: 6
  selector:
    matchLabels:
      app: kargo-demo
  strategy:
    canary:
      steps:
      - setWeight: 50
      - pause:
          duration: 5m
      - setWeight: 100
  template:
    metadata:
      labels:
        app: kargo-demo
    spec:
      containers:
      - image: public.ecr.aws/nginx/nginx:1.23.3
        name: nginx
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: content
          readOnly: true
      volumes:
      - configMap:
          name: kargo-demo-content
        name: content
