apiVersion: v1
kind: Service
metadata:
  name: kargo-demo-active
spec:
  ports:
  - nodePort: placeholder
    port: 3000
    protocol: TCP
    targetPort: 80
  selector:
    app: kargo-demo
  type: NodePort
