apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: kargo-demo
spec:
  replicas: 4
  selector:
    matchLabels:
      app: kargo-demo
  template:
    metadata:
      labels:
        app: kargo-demo
    spec:
      containers:
      - name: nginx
        image: public.ecr.aws/nginx/nginx:1.26.0
        volumeMounts:
        - name: content
          mountPath: /usr/share/nginx/html
          readOnly: true
      volumes:
      - name: content
        configMap:
          name: kargo-demo-content
  #strategy:
  #  canary:
  #    steps:
  #      - setWeight: 50
  #      - pause: {duration: 5m}
  #      - setWeight: 100
  strategy:
    blueGreen:
      activeService: kargo-demo-active
      previewService: kargo-demo-preview
      autoPromotionEnabled: false
      #autoPromotionSeconds: 60

